### ISSUE TITLE
Soundfilter

### ISSUE THREAD

**Issue by Ghoulfriend** [Sebane1/FFXIVVoicePackCreator#1]
Why not use the dalamud plugin soundfilter for identification of voice files?

**Comment by Sebane1** [comment]
I actually wasn't aware the plugin existed, but definitely appears to be a very good alternative for a portion of this tools functionality.

Will probably accelerate my plans to simply have selections for what voice and race combination people want to replace sounds on.

**Comment by Sebane1** [comment]
Tool has now been updated so that guessing file names is no longer a required process of making custom voice packs.
I consolidated the data I grabbed with the help of Sound Filter.
