### ISSUE TITLE
 Lssue with Export Function in RoleplayingVoiceDalamud

### ISSUE THREAD

**Issue by 1062390647** [Sebane1/FFXIVVoicePackCreator#12]
I encountered some issues while exporting audio files using the FFXIVVoicePackCreator tool.
I have successfully downloaded and run the Artemis Roleplaying Kit plugin in the game, but when I try to export the organized audio files in FFXIVVoicePackCreator, I keep receiving error messages saying "Unable to find the Artemis Roleplaying Kit configuration" and "No files were exported.NO Artemis Roleplay Kit was found." Although I have followed the recommended installation and setup steps, these errors still occur.
These issues seem to point to problems with configuration recognition or interaction between the plugin and game instances. 
![屏幕截图2024-03-06 171804](https://github.com/Sebane1/FFXIVVoicePackCreator/assets/108111620/5bc3d5a0-3ce7-4964-a444-3dd9cc5d003b)

**Comment by MicaTheWanderer** [comment]
Did you figure this out?
