### ISSUE TITLE
bug: Wrong SCD file

### ISSUE THREAD

**Issue by ratikalXIV** [Sebane1/FFXIVVoicePackCreator#3]
SCD file 7454* is Midlander Male voice 10 when the app states its 7451*
![Pasted image 20221123220342](https://user-images.githubusercontent.com/10054535/203687891-aaae5ff5-bc07-428f-a204-dca7dc3d8607.png)

**Comment by Sebane1** [comment]
Are you able to double check your readout? 
![image](https://user-images.githubusercontent.com/7157688/203688818-1fd7d354-5453-4b15-a78d-34da2f7800a5.png)

**Comment by ratikalXIV** [comment]
Yeah, I think I misread something when I was testing. Sorry!
