### ISSUE TITLE
Can't open on Windows 11 + DotNet 7.0.1

### ISSUE THREAD

**Issue by z32o** [Sebane1/FFXIVVoicePackCreator#6]
Keeps prompting to install dotnet 7.0.0 and offers to download it

**Comment by Sebane1** [comment]
Install .net desktop runtime 7.0 (not to be confused with .net runtime 7.0) https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.1-windows-x64-installer
